package Bomberman;

public enum GameEntity {
    PLAYER, BOMB, VIRTUAL_BOMB, FLAME, WALL, BRICK, DOOR, BRICK_BREAK, POWERUP_BOMBS, POWERUP_FLAMES, POWERUP_SPEED, POWERUP_FLAMEPASS, POWERUP_LIFE,
    BAlLOM, ONIL
}
